// <auto-generated />
using System;
using Bookify.DataAccess.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bookify.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241101215715_ModifyUser")]
    partial class ModifyUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("SerialNumber", "Shared")
                .StartsAt(10000001L)
                .IncrementsBy(2);

            modelBuilder.Entity("Bookify.Entities.entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FirstModificationByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FirstModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LastModificationByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedByUserId = 1,
                            CreationTime = new DateTime(2024, 11, 1, 23, 57, 13, 914, DateTimeKind.Local).AddTicks(2342),
                            IsDeleted = false,
                            Name = "Taha Hussien",
                            Nationality = "Egypt"
                        },
                        new
                        {
                            Id = 2,
                            CreatedByUserId = 1,
                            CreationTime = new DateTime(2024, 11, 1, 23, 57, 13, 914, DateTimeKind.Local).AddTicks(2353),
                            IsDeleted = false,
                            Name = "Naguib Mahfouz",
                            Nationality = "Egypt"
                        },
                        new
                        {
                            Id = 3,
                            CreatedByUserId = 1,
                            CreationTime = new DateTime(2024, 11, 1, 23, 57, 13, 914, DateTimeKind.Local).AddTicks(2357),
                            IsDeleted = false,
                            Name = "Mahmoud Darwish",
                            Nationality = "Palestine"
                        },
                        new
                        {
                            Id = 4,
                            CreatedByUserId = 1,
                            CreationTime = new DateTime(2024, 11, 1, 23, 57, 13, 914, DateTimeKind.Local).AddTicks(2360),
                            IsDeleted = false,
                            Name = "Khalil Gibran",
                            Nationality = "Lebanon"
                        },
                        new
                        {
                            Id = 5,
                            CreatedByUserId = 1,
                            CreationTime = new DateTime(2024, 11, 1, 23, 57, 13, 914, DateTimeKind.Local).AddTicks(2364),
                            IsDeleted = false,
                            Name = "Adonis",
                            Nationality = "Syria"
                        },
                        new
                        {
                            Id = 6,
                            CreatedByUserId = 1,
                            CreationTime = new DateTime(2024, 11, 1, 23, 57, 13, 914, DateTimeKind.Local).AddTicks(2369),
                            IsDeleted = false,
                            Name = "Hanan al-Shaykh",
                            Nationality = "Lebanon"
                        },
                        new
                        {
                            Id = 7,
                            CreatedByUserId = 1,
                            CreationTime = new DateTime(2024, 11, 1, 23, 57, 13, 914, DateTimeKind.Local).AddTicks(2372),
                            IsDeleted = false,
                            Name = "Ahlam Mosteghanemi",
                            Nationality = "Algeria"
                        },
                        new
                        {
                            Id = 8,
                            CreatedByUserId = 1,
                            CreationTime = new DateTime(2024, 11, 1, 23, 57, 13, 914, DateTimeKind.Local).AddTicks(2375),
                            IsDeleted = false,
                            Name = "Ibrahim Nasrallah",
                            Nationality = "Palestine"
                        },
                        new
                        {
                            Id = 9,
                            CreatedByUserId = 1,
                            CreationTime = new DateTime(2024, 11, 1, 23, 57, 13, 914, DateTimeKind.Local).AddTicks(2379),
                            IsDeleted = false,
                            Name = "Hanan al-Shaykh",
                            Nationality = "Lebanon"
                        },
                        new
                        {
                            Id = 10,
                            CreatedByUserId = 1,
                            CreationTime = new DateTime(2024, 11, 1, 23, 57, 13, 914, DateTimeKind.Local).AddTicks(2383),
                            IsDeleted = false,
                            Name = "Nawal El Saadawi",
                            Nationality = "Egypt"
                        },
                        new
                        {
                            Id = 11,
                            CreatedByUserId = 1,
                            CreationTime = new DateTime(2024, 11, 1, 23, 57, 13, 914, DateTimeKind.Local).AddTicks(2386),
                            IsDeleted = false,
                            Name = "Yasmina Khadra",
                            Nationality = "Algeria"
                        },
                        new
                        {
                            Id = 12,
                            CreatedByUserId = 1,
                            CreationTime = new DateTime(2024, 11, 1, 23, 57, 13, 914, DateTimeKind.Local).AddTicks(2389),
                            IsDeleted = false,
                            Name = "Salman Rushdie",
                            Nationality = "India"
                        },
                        new
                        {
                            Id = 13,
                            CreatedByUserId = 1,
                            CreationTime = new DateTime(2024, 11, 1, 23, 57, 13, 914, DateTimeKind.Local).AddTicks(2392),
                            IsDeleted = false,
                            Name = "Orhan Pamuk",
                            Nationality = "Turkey"
                        },
                        new
                        {
                            Id = 14,
                            CreatedByUserId = 1,
                            CreationTime = new DateTime(2024, 11, 1, 23, 57, 13, 914, DateTimeKind.Local).AddTicks(2396),
                            IsDeleted = false,
                            Name = "Elif Shafak",
                            Nationality = "Turkey"
                        },
                        new
                        {
                            Id = 15,
                            CreatedByUserId = 1,
                            CreationTime = new DateTime(2024, 11, 1, 23, 57, 13, 914, DateTimeKind.Local).AddTicks(2399),
                            IsDeleted = false,
                            Name = "Amitav Ghosh",
                            Nationality = "India"
                        });
                });

            modelBuilder.Entity("Bookify.Entities.entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FirstModificationByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FirstModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hall")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailableForRental")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LastModificationByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PublishedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("Title", "AuthorId")
                        .IsUnique();

                    b.ToTable("Books", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            CreatedByUserId = 1,
                            CreationTime = new DateTime(2024, 11, 1, 23, 57, 13, 914, DateTimeKind.Local).AddTicks(9899),
                            Description = "A sweeping saga of a family in Cairo during the early 20th century.",
                            Hall = "Main Hall",
                            ImageUrl = "https://example.com/cairo_trilogy.jpg",
                            IsAvailableForRental = false,
                            IsDeleted = false,
                            Price = 150m,
                            PublishedOn = new DateTime(1956, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Publishing House",
                            Title = "The Cairo Trilogy",
                            Type = "Drama"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            CreatedByUserId = 1,
                            CreationTime = new DateTime(2024, 11, 1, 23, 57, 13, 914, DateTimeKind.Local).AddTicks(9913),
                            Description = "The first book in the Cairo Trilogy, focusing on family life in Cairo.",
                            Hall = "Main Hall",
                            ImageUrl = "https://example.com/palace_walk.jpg",
                            IsAvailableForRental = false,
                            IsDeleted = false,
                            Price = 120m,
                            PublishedOn = new DateTime(1956, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Publishing House",
                            Title = "Palace Walk",
                            Type = "Drama"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            CreatedByUserId = 1,
                            CreationTime = new DateTime(2024, 11, 1, 23, 57, 13, 914, DateTimeKind.Local).AddTicks(9918),
                            Description = "A postcolonial narrative exploring identity and belonging.",
                            Hall = "Main Hall",
                            ImageUrl = "https://example.com/season_of_migration.jpg",
                            IsAvailableForRental = false,
                            IsDeleted = false,
                            Price = 130m,
                            PublishedOn = new DateTime(1966, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Publishing House",
                            Title = "Season of Migration to the North",
                            Type = "Fiction"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 3,
                            CreatedByUserId = 1,
                            CreationTime = new DateTime(2024, 11, 1, 23, 57, 13, 914, DateTimeKind.Local).AddTicks(9923),
                            Description = "A collection of poetic essays covering various aspects of life.",
                            Hall = "Poetry Section",
                            ImageUrl = "https://example.com/the_prophet.jpg",
                            IsAvailableForRental = false,
                            IsDeleted = false,
                            Price = 90m,
                            PublishedOn = new DateTime(1923, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Publishing House",
                            Title = "The Prophet",
                            Type = "Poetry"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 4,
                            CreatedByUserId = 1,
                            CreationTime = new DateTime(2024, 11, 1, 23, 57, 13, 914, DateTimeKind.Local).AddTicks(9927),
                            Description = "A historical novel set in Egypt and America, intertwining love stories.",
                            Hall = "Main Hall",
                            ImageUrl = "https://example.com/map_of_love.jpg",
                            IsAvailableForRental = false,
                            IsDeleted = false,
                            Price = 140m,
                            PublishedOn = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Publishing House",
                            Title = "The Map of Love",
                            Type = "HistoricalFiction"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 5,
                            CreatedByUserId = 1,
                            CreationTime = new DateTime(2024, 11, 1, 23, 57, 13, 914, DateTimeKind.Local).AddTicks(9934),
                            Description = "A novel set in a once-grand building in downtown Cairo.",
                            Hall = "Main Hall",
                            ImageUrl = "https://example.com/yacoubian_building.jpg",
                            IsAvailableForRental = false,
                            IsDeleted = false,
                            Price = 110m,
                            PublishedOn = new DateTime(2002, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Publishing House",
                            Title = "The Yacoubian Building",
                            Type = "Fiction"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 6,
                            CreatedByUserId = 1,
                            CreationTime = new DateTime(2024, 11, 1, 23, 57, 13, 914, DateTimeKind.Local).AddTicks(9939),
                            Description = "A poignant coming-of-age story set in Egypt.",
                            Hall = "Main Hall",
                            ImageUrl = "https://example.com/open_door.jpg",
                            IsAvailableForRental = false,
                            IsDeleted = false,
                            Price = 100m,
                            PublishedOn = new DateTime(1960, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Publishing House",
                            Title = "The Open Door",
                            Type = "Fiction"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 7,
                            CreatedByUserId = 1,
                            CreationTime = new DateTime(2024, 11, 1, 23, 57, 13, 914, DateTimeKind.Local).AddTicks(9943),
                            Description = "A novel that blends Eastern and Western philosophies.",
                            Hall = "Main Hall",
                            ImageUrl = "https://example.com/book_of_khalid.jpg",
                            IsAvailableForRental = false,
                            IsDeleted = false,
                            Price = 85m,
                            PublishedOn = new DateTime(1911, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Publishing House",
                            Title = "The Book of Khalid",
                            Type = "Fiction"
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 8,
                            CreatedByUserId = 1,
                            CreationTime = new DateTime(2024, 11, 1, 23, 57, 13, 914, DateTimeKind.Local).AddTicks(9947),
                            Description = "An exploration of spirituality and identity.",
                            Hall = "Main Hall",
                            ImageUrl = "https://example.com/return_of_the_spirit.jpg",
                            IsAvailableForRental = false,
                            IsDeleted = false,
                            Price = 125m,
                            PublishedOn = new DateTime(1933, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Publishing House",
                            Title = "The Return of the Spirit",
                            Type = "Fiction"
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 9,
                            CreatedByUserId = 1,
                            CreationTime = new DateTime(2024, 11, 1, 23, 57, 13, 914, DateTimeKind.Local).AddTicks(9953),
                            Description = "A novel set in the Ottoman Empire, blending art and politics.",
                            Hall = "Main Hall",
                            ImageUrl = "https://example.com/my_name_is_red.jpg",
                            IsAvailableForRental = false,
                            IsDeleted = false,
                            Price = 135m,
                            PublishedOn = new DateTime(1998, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Publishing House",
                            Title = "My Name is Red",
                            Type = "Fiction"
                        });
                });

            modelBuilder.Entity("Bookify.Entities.entities.BookCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("BookCategories", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            BookId = 1
                        },
                        new
                        {
                            CategoryId = 1,
                            BookId = 2
                        },
                        new
                        {
                            CategoryId = 2,
                            BookId = 3
                        },
                        new
                        {
                            CategoryId = 3,
                            BookId = 4
                        },
                        new
                        {
                            CategoryId = 2,
                            BookId = 5
                        },
                        new
                        {
                            CategoryId = 2,
                            BookId = 6
                        },
                        new
                        {
                            CategoryId = 2,
                            BookId = 7
                        },
                        new
                        {
                            CategoryId = 2,
                            BookId = 8
                        },
                        new
                        {
                            CategoryId = 2,
                            BookId = 9
                        },
                        new
                        {
                            CategoryId = 2,
                            BookId = 10
                        });
                });

            modelBuilder.Entity("Bookify.Entities.entities.BookCopy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("EditionNumber")
                        .HasColumnType("int");

                    b.Property<int?>("FirstModificationByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FirstModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAvailableForRental")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LastModificationByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SerialNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR Shared.SerialNumber");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("BookCopies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            CreatedByUserId = 0,
                            CreationTime = new DateTime(2024, 7, 24, 23, 57, 13, 915, DateTimeKind.Local).AddTicks(2569),
                            EditionNumber = 1,
                            IsAvailableForRental = true,
                            IsDeleted = false,
                            SerialNumber = 0
                        },
                        new
                        {
                            Id = 2,
                            BookId = 1,
                            CreatedByUserId = 0,
                            CreationTime = new DateTime(2024, 4, 15, 23, 57, 13, 915, DateTimeKind.Local).AddTicks(2583),
                            EditionNumber = 2,
                            IsAvailableForRental = false,
                            IsDeleted = false,
                            SerialNumber = 0
                        },
                        new
                        {
                            Id = 3,
                            BookId = 2,
                            CreatedByUserId = 0,
                            CreationTime = new DateTime(2024, 9, 12, 23, 57, 13, 915, DateTimeKind.Local).AddTicks(2588),
                            EditionNumber = 1,
                            IsAvailableForRental = true,
                            IsDeleted = false,
                            SerialNumber = 0
                        },
                        new
                        {
                            Id = 4,
                            BookId = 2,
                            CreatedByUserId = 0,
                            CreationTime = new DateTime(2024, 6, 4, 23, 57, 13, 915, DateTimeKind.Local).AddTicks(2594),
                            EditionNumber = 2,
                            IsAvailableForRental = false,
                            IsDeleted = false,
                            SerialNumber = 0
                        },
                        new
                        {
                            Id = 5,
                            BookId = 3,
                            CreatedByUserId = 0,
                            CreationTime = new DateTime(2024, 10, 22, 23, 57, 13, 915, DateTimeKind.Local).AddTicks(2598),
                            EditionNumber = 1,
                            IsAvailableForRental = true,
                            IsDeleted = false,
                            SerialNumber = 0
                        },
                        new
                        {
                            Id = 6,
                            BookId = 3,
                            CreatedByUserId = 0,
                            CreationTime = new DateTime(2024, 10, 2, 23, 57, 13, 915, DateTimeKind.Local).AddTicks(2606),
                            EditionNumber = 2,
                            IsAvailableForRental = true,
                            IsDeleted = false,
                            SerialNumber = 0
                        },
                        new
                        {
                            Id = 7,
                            BookId = 4,
                            CreatedByUserId = 0,
                            CreationTime = new DateTime(2024, 9, 2, 23, 57, 13, 915, DateTimeKind.Local).AddTicks(2611),
                            EditionNumber = 1,
                            IsAvailableForRental = false,
                            IsDeleted = false,
                            SerialNumber = 0
                        },
                        new
                        {
                            Id = 8,
                            BookId = 4,
                            CreatedByUserId = 0,
                            CreationTime = new DateTime(2024, 8, 3, 23, 57, 13, 915, DateTimeKind.Local).AddTicks(2615),
                            EditionNumber = 2,
                            IsAvailableForRental = true,
                            IsDeleted = false,
                            SerialNumber = 0
                        },
                        new
                        {
                            Id = 9,
                            BookId = 5,
                            CreatedByUserId = 0,
                            CreationTime = new DateTime(2024, 10, 27, 23, 57, 13, 915, DateTimeKind.Local).AddTicks(2621),
                            EditionNumber = 1,
                            IsAvailableForRental = true,
                            IsDeleted = false,
                            SerialNumber = 0
                        },
                        new
                        {
                            Id = 10,
                            BookId = 5,
                            CreatedByUserId = 0,
                            CreationTime = new DateTime(2024, 10, 7, 23, 57, 13, 915, DateTimeKind.Local).AddTicks(2627),
                            EditionNumber = 2,
                            IsAvailableForRental = false,
                            IsDeleted = false,
                            SerialNumber = 0
                        },
                        new
                        {
                            Id = 11,
                            BookId = 6,
                            CreatedByUserId = 0,
                            CreationTime = new DateTime(2024, 9, 27, 23, 57, 13, 915, DateTimeKind.Local).AddTicks(2632),
                            EditionNumber = 1,
                            IsAvailableForRental = true,
                            IsDeleted = false,
                            SerialNumber = 0
                        },
                        new
                        {
                            Id = 12,
                            BookId = 6,
                            CreatedByUserId = 0,
                            CreationTime = new DateTime(2024, 8, 18, 23, 57, 13, 915, DateTimeKind.Local).AddTicks(2636),
                            EditionNumber = 2,
                            IsAvailableForRental = true,
                            IsDeleted = false,
                            SerialNumber = 0
                        },
                        new
                        {
                            Id = 13,
                            BookId = 7,
                            CreatedByUserId = 0,
                            CreationTime = new DateTime(2024, 7, 4, 23, 57, 13, 915, DateTimeKind.Local).AddTicks(2643),
                            EditionNumber = 1,
                            IsAvailableForRental = false,
                            IsDeleted = false,
                            SerialNumber = 0
                        },
                        new
                        {
                            Id = 14,
                            BookId = 7,
                            CreatedByUserId = 0,
                            CreationTime = new DateTime(2024, 5, 5, 23, 57, 13, 915, DateTimeKind.Local).AddTicks(2648),
                            EditionNumber = 2,
                            IsAvailableForRental = true,
                            IsDeleted = false,
                            SerialNumber = 0
                        },
                        new
                        {
                            Id = 15,
                            BookId = 8,
                            CreatedByUserId = 0,
                            CreationTime = new DateTime(2024, 4, 15, 23, 57, 13, 915, DateTimeKind.Local).AddTicks(2652),
                            EditionNumber = 1,
                            IsAvailableForRental = true,
                            IsDeleted = false,
                            SerialNumber = 0
                        });
                });

            modelBuilder.Entity("Bookify.Entities.entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FirstModificationByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FirstModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LastModificationByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedByUserId = 1,
                            CreationTime = new DateTime(2024, 11, 1, 23, 57, 13, 915, DateTimeKind.Local).AddTicks(5180),
                            IsDeleted = false,
                            Name = "Fighting"
                        },
                        new
                        {
                            Id = 2,
                            CreatedByUserId = 1,
                            CreationTime = new DateTime(2024, 11, 1, 23, 57, 13, 915, DateTimeKind.Local).AddTicks(5205),
                            IsDeleted = false,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 3,
                            CreatedByUserId = 1,
                            CreationTime = new DateTime(2024, 11, 1, 23, 57, 13, 915, DateTimeKind.Local).AddTicks(5208),
                            IsDeleted = false,
                            Name = "Fiction"
                        });
                });

            modelBuilder.Entity("Bookify.Entities.entities.Identity.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", "UserManagement");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "5880A236-CEC4-4463-941A-47F6DD9873A3",
                            CreatedOn = new DateTime(2024, 11, 1, 21, 57, 13, 915, DateTimeKind.Utc).AddTicks(7879),
                            IsDefault = false,
                            IsDeleted = false,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "5880A236-F389-4541-BBA4-7CD4EB900950",
                            CreatedOn = new DateTime(2024, 11, 1, 21, 57, 13, 915, DateTimeKind.Utc).AddTicks(7935),
                            IsDefault = true,
                            IsDeleted = false,
                            Name = "Member",
                            NormalizedName = "MEMBER"
                        });
                });

            modelBuilder.Entity("Bookify.Entities.entities.Identity.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasFilter("[UserName] IS NOT NULL");

                    b.ToTable("Users", "UserManagement");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "A4FEA470-1B47-4011-9A71-FE3AD504CE6A",
                            CreatedOn = new DateTime(2024, 11, 1, 21, 57, 13, 916, DateTimeKind.Utc).AddTicks(971),
                            Email = "blalhamd48@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Bilal",
                            IsDeleted = false,
                            IsDisabled = false,
                            LastName = "Sayed",
                            LockoutEnabled = false,
                            NormalizedEmail = "BLALHAMD48@GMAIL.COM",
                            NormalizedUserName = "BLALHAMD48",
                            PasswordHash = "AQAAAAIAAYagAAAAEBea2/0J0OOBEQM19s69CJ51OpW1orVxt2lld5k9GOO0D59RmVOD+0Dx+NXzabpY0A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1D32688429B44DD296E29A64DDB76779",
                            TwoFactorEnabled = false,
                            UserName = "blalhamd48"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", "UserManagement");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "permissions",
                            ClaimValue = "Roles:GetAll",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            ClaimType = "permissions",
                            ClaimValue = "Roles:Add",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 3,
                            ClaimType = "permissions",
                            ClaimValue = "Roles:Update",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 4,
                            ClaimType = "permissions",
                            ClaimValue = "Roles:Delete",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 5,
                            ClaimType = "permissions",
                            ClaimValue = "Users:GetAll",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 6,
                            ClaimType = "permissions",
                            ClaimValue = "Users:Add",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 7,
                            ClaimType = "permissions",
                            ClaimValue = "Users:Update",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 8,
                            ClaimType = "permissions",
                            ClaimValue = "Users:Delete",
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", "UserManagement");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogin", "UserManagement");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "UserManagement");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserToken", "UserManagement");
                });

            modelBuilder.Entity("Bookify.Entities.entities.Book", b =>
                {
                    b.HasOne("Bookify.Entities.entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Bookify.Entities.entities.BookCategory", b =>
                {
                    b.HasOne("Bookify.Entities.entities.Book", "Book")
                        .WithMany("Categories")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bookify.Entities.entities.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Bookify.Entities.entities.BookCopy", b =>
                {
                    b.HasOne("Bookify.Entities.entities.Book", "Book")
                        .WithMany("Copies")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Bookify.Entities.entities.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Bookify.Entities.entities.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Bookify.Entities.entities.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Bookify.Entities.entities.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bookify.Entities.entities.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Bookify.Entities.entities.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bookify.Entities.entities.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Bookify.Entities.entities.Book", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Copies");
                });

            modelBuilder.Entity("Bookify.Entities.entities.Category", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
